# GNN Processing Pipeline Configuration
# This file contains configuration settings for the GNN processing pipeline

# Pipeline execution settings
pipeline:
  # Enable/disable pipeline execution
  enabled: true
  
  # Pipeline steps to execute (0-21)
  # Leave empty to run all steps
  steps: []
  
  # Skip specific steps
  skip_steps: []
  
  # Force execution of specific steps
  force_steps: []
  
  # Parallel execution settings
  parallel:
    enabled: false
    max_workers: 4
  
  # Timeout settings (in seconds)
  timeout:
    step: 3600  # 1 hour per step
    total: 7200  # 2 hours total

# UV environment settings
uv:
  # UV environment management
  recreate_uv_env: false
  
  # UV environment directory (UV standard)
  uv_env_dir: ".venv"
  
  # UV sync settings
  sync:
    # Install development dependencies
    dev: false
    
    # Install optional dependency groups
    extras: []
    
    # Upgrade packages
    upgrade: false
    
    # Fast sync mode
    fast: true

# Input/output settings
io:
  # Input directory for GNN files
  input_dir: "input/gnn_files"
  
  # Output directory for pipeline artifacts
  output_dir: "output"
  
  # Temporary directory
  temp_dir: "temp"
  
  # Log directory
  log_dir: "logs"

# Logging settings
logging:
  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  level: "INFO"
  
  # Log format
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Log file settings
  file:
    enabled: true
    max_size: "10MB"
    backup_count: 5

# Validation settings
validation:
  # Enable validation checks
  enabled: true
  
  # Strict validation mode
  strict: false
  
  # Validation timeout (seconds)
  timeout: 300
  
  # POMDP-specific validation
  pomdp:
    # Enable POMDP mode for Active Inference models
    enabled: true
    
    # Path to ontology terms file
    ontology_file: "input/ontology_terms.json"
    
    # POMDP validation strictness
    strict_ontology: true
    strict_dimensions: true
    
    # POMDP-specific analysis
    analyze_complexity: true
    estimate_resources: true
    generate_summary: true

# Performance settings
performance:
  # Memory limit (MB)
  memory_limit: 4096
  
  # CPU limit (cores)
  cpu_limit: 4
  
  # Cache settings
  cache:
    enabled: true
    max_size: "1GB"
    ttl: 3600  # 1 hour

# Security settings
security:
  # Enable security checks
  enabled: true
  
  # Allow network access
  network_access: true
  
  # File permissions
  file_permissions: "644" 