module Classic_Active_Inference_POMDP_Agent_v1

// GNN Model: Classic Active Inference POMDP Agent v1
// Generated by AlloySerializer

// Variable signatures
sig A {
  value: Int,
  dimensions: seq Int  // [3, 3]
}

sig B {
  value: Int,
  dimensions: seq Int  // [3, 3, 3]
}

sig C {
  value: Int,
  dimensions: seq Int  // [3]
}

sig D {
  value: Int,
  dimensions: seq Int  // [3]
}

sig E {
  value: Int,
  dimensions: seq Int  // [3]
}

// Connection constraints
fact Connections {
  // Connection 1: A -> s
  some A and some s
  // Connection 2: B -> s_prime
  some B and some s_prime
  // Connection 3: C -> o
  some C and some o
  // Connection 4: D -> s
  some D and some s
  // Connection 5: E -> π
  some E and some V_
  // Connection 6: s -> o
  some s and some o
  // Connection 7: π -> u
  some V_ and some u
  // Connection 8: u -> s_prime
  some u and some s_prime
}

// Model validity predicate
pred Classic_Active_Inference_POMDP_Agent_v1Valid {
  // All variables must exist
  some A
  some B
  some C
  some D
  some E
}

// Parameter constraints
fact Parameters {
  // Parameter: A = []
  // Parameter: B = []
  // Parameter: C = []
  // Parameter: D = []
  // Parameter: E = []
}


/* MODEL_DATA: {"model_name":"Classic Active Inference POMDP Agent v1","version":"1.0","annotation":"","variables":[{"name":"A","var_type":"likelihood_matrix","data_type":"float","dimensions":[3,3],"description":"likelihood_matrix"},{"name":"B","var_type":"transition_matrix","data_type":"float","dimensions":[3,3,3],"description":"transition_matrix"},{"name":"C","var_type":"preference_vector","data_type":"float","dimensions":[3],"description":"preference_vector"},{"name":"D","var_type":"prior_vector","data_type":"float","dimensions":[3],"description":"prior_vector"},{"name":"E","var_type":"policy","data_type":"float","dimensions":[3],"description":"policy"}],"connections":[{"source_variables":["A"],"target_variables":["s"],"connection_type":"directed","weight":null,"description":null},{"source_variables":["B"],"target_variables":["s_prime"],"connection_type":"directed","weight":null,"description":null},{"source_variables":["C"],"target_variables":["o"],"connection_type":"directed","weight":null,"description":null},{"source_variables":["D"],"target_variables":["s"],"connection_type":"directed","weight":null,"description":null},{"source_variables":["E"],"target_variables":["\u03c0"],"connection_type":"directed","weight":null,"description":null},{"source_variables":["s"],"target_variables":["o"],"connection_type":"directed","weight":null,"description":null},{"source_variables":["\u03c0"],"target_variables":["u"],"connection_type":"directed","weight":null,"description":null},{"source_variables":["u"],"target_variables":["s_prime"],"connection_type":"directed","weight":null,"description":null}],"parameters":[{"name":"A","value":[],"type_hint":null,"description":null},{"name":"B","value":[],"type_hint":null,"description":null},{"name":"C","value":[],"type_hint":null,"description":null},{"name":"D","value":[],"type_hint":null,"description":null},{"name":"E","value":[],"type_hint":null,"description":null}],"equations":[],"time_specification":{},"ontology_mappings":[]} */
