"""GUI 1 runner: headless artifact generation and interactive Gradio launch.

Public functions: run_gui
"""

from __future__ import annotations

import logging
import time
from pathlib import Path

from gnn.utils.pipeline_template import (
    log_step_error,
    log_step_success,
)

from ..backend import (
    detect_gradio_backend,
    write_json_atomically,
    write_text_atomically,
)
from ..runner import launch_gradio_in_thread, load_first_markdown, resolve_output_root

# Detected once at import; tests reload this module after stubbing ``gradio``
# in sys.modules, so this module-level detection must stay.
_GUI_STATUS = detect_gradio_backend()
gr = _GUI_STATUS.module
_GUI_BACKEND = _GUI_STATUS.name
_GUI_BACKEND_REASON = _GUI_STATUS.reason

_FALLBACK_STARTER_MD = (
    "# GNN Model\n\n"
    "components:\n"
    "  - name: example_component\n"
    "    type: observation\n"
    "    states: [s1, s2]\n\n"
)
_GUI1_PORT = 7860


def run_gui(
    target_dir: Path,
    output_dir: Path,
    logger: logging.Logger,
    verbose: bool = False,
    headless: bool = False,
    export_filename: str = "constructed_model.md",
    open_browser: bool = True,
) -> bool:
    """
    Run GUI 1: generate headless artifacts or launch the interactive constructor.

    Args:
        target_dir: Directory containing GNN files to load as starter content
        output_dir: Output directory for results
        logger: Logger instance
        verbose: Enable verbose logging
        headless: Generate artifacts only, without launching a server
        export_filename: Filename for the exported model
        open_browser: Open the browser automatically in interactive mode

    Returns:
        True on success, False on failure
    """
    try:
        output_root = resolve_output_root(output_dir)
        output_root.mkdir(parents=True, exist_ok=True)

        starter_md = load_first_markdown(target_dir) or _FALLBACK_STARTER_MD

        if headless or _GUI_BACKEND is None:
            starter_md = f"<!-- HEADLESS ARTIFACT: Generated by GUI 1 Constructor -->\n{starter_md}"

        starter_path = output_root / export_filename
        write_text_atomically(starter_path, starter_md)

        if headless or _GUI_BACKEND is None:
            # Enhanced recovery handling for missing GUI backend
            if _GUI_BACKEND is None:
                logger.info(
                    "Gradio not available; generating static headless GUI 1 "
                    "artifacts (expected for default pipeline; use "
                    "uv sync --extra gui for interactive UI)"
                )
                if _GUI_BACKEND_REASON:
                    logger.info(f"GUI backend unavailable: {_GUI_BACKEND_REASON}")
                logger.info("Install GUI support with: uv sync --extra gui")
            else:
                logger.info(
                    "📦 Running GUI 1 in HEADLESS mode - generating artifacts only"
                )

            # Create comprehensive recovery status report
            fallback_status: dict[str, object] = {
                "backend": _GUI_BACKEND or "none",
                "launched": False,
                "export_file": str(starter_path),
                "gui_type": "form_based_constructor",
                "status": "fallback_mode" if _GUI_BACKEND is None else "headless_mode",
                "reason": "gradio_not_available"
                if _GUI_BACKEND is None
                else "headless_requested",
                "backend_reason": _GUI_BACKEND_REASON,
                "recommendations": [
                    "Install with: uv sync --extra gui",
                    "Run with --interactive for full GUI experience",
                    "Use generated template as starting point for manual editing",
                ]
                if _GUI_BACKEND is None
                else [
                    "Generated template available for manual editing",
                    "Run with --interactive to launch GUI server on port 7860",
                ],
            }

            write_json_atomically(output_root / "gui_status.json", fallback_status)

            log_step_success(
                logger,
                f"GUI 1 artifacts generated ({'recovery' if _GUI_BACKEND is None else 'headless'}). Export: {starter_path}",
            )
            return True

        # Interactive mode - build and launch Gradio GUI
        logger.info("🔧 Building Form-based Interactive GNN Constructor...")
        from .ui import build_gui

        demo = build_gui(
            markdown_text=starter_md, export_path=starter_path, logger=logger
        )
        logger.info("✅ Form-based Constructor UI built successfully")

        # Launch GUI server - stay open but allow other GUIs to launch too
        logger.info(
            f"🌐 Launching GUI 1 on http://localhost:{_GUI1_PORT} (open_browser={open_browser})"
        )
        launch_gradio_in_thread(demo, port=_GUI1_PORT, open_browser=open_browser)

        # Give it a moment to start and verify
        time.sleep(3)
        logger.info(f"🎮 GUI 1 is running on http://localhost:{_GUI1_PORT}")
        logger.info(
            "🔍 Features: Component management, state space editing, live markdown sync"
        )

        # Record availability artifact
        write_json_atomically(
            output_root / "gui_status.json",
            {
                "backend": _GUI_BACKEND,
                "launched": True,
                "export_file": str(starter_path),
                "gui_type": "form_based_constructor",
                "port": _GUI1_PORT,
                "url": f"http://localhost:{_GUI1_PORT}",
            },
        )

        log_step_success(logger, "GUI 1 launched successfully")
        return True
    except Exception as e:
        log_step_error(logger, f"GUI launch failed: {e}")
        return False
