#!/usr/bin/env python3
"""
NumPyro POMDP Simulation: numpyro_pomdp

Auto-generated by GNN Pipeline — NumPyro renderer.
Uses numpyro.distributions.Categorical for probabilistic sampling
within the standard Active Inference generative loop.
"""
import json
import os
import sys
import time
from pathlib import Path

try:
    import jax
    import jax.numpy as jnp
    import jax.random as jrandom
except ImportError:
    print("ERROR: JAX not installed. Install with: uv sync --extra probabilistic-programming")
    sys.exit(1)

try:
    import numpyro
    import numpyro.distributions as dist
except ImportError:
    print("ERROR: NumPyro not installed. Install with: uv sync --extra probabilistic-programming")
    sys.exit(1)

import numpy as np


def run_simulation(seed: int = 42):
    """Run POMDP simulation with NumPyro distributions."""
    start_time = time.time()
    key = jrandom.PRNGKey(seed)

    # --- Model Parameters ---
    num_states = 3
    num_obs = 3
    num_actions = 2
    T = 15

    A = jnp.array([
        [1.000000, 0.000000, 0.000000],
        [0.000000, 1.000000, 0.000000],
        [0.000000, 0.000000, 1.000000]
    ])
    C = jnp.array([0.000000, 0.000000, 0.000000])
    D = jnp.array([0.500000, 0.300000, 0.200000])
    
    B = jnp.tile(jnp.array([
        [1.000000, 0.000000, 0.000000],
        [0.000000, 1.000000, 0.000000],
        [0.000000, 0.000000, 1.000000]
    ])[:, :, None], (1, 1, 2))

    # --- Simulation State ---
    beliefs_history = []
    actions_history = []
    observations_history = []
    efe_history = []

    # Initialize true state from prior using NumPyro
    key, subkey = jrandom.split(key)
    true_state = int(dist.Categorical(probs=D).sample(subkey))
    beliefs = D.copy()

    for t in range(T):
        # 1. Generate observation
        key, subkey = jrandom.split(key)
        obs_probs = A[:, true_state]
        obs_probs = obs_probs / obs_probs.sum()
        observation = int(dist.Categorical(probs=obs_probs).sample(subkey))

        # 2. Bayesian belief update
        likelihood = A[observation, :]
        posterior = likelihood * beliefs
        posterior = posterior / (jnp.sum(posterior) + 1e-16)
        beliefs = posterior

        # 3. Expected Free Energy for each action
        efe = jnp.zeros(num_actions)
        for a_idx in range(num_actions):
            B_a = B[:, :, a_idx]
            predicted_state = B_a @ beliefs
            predicted_obs = A @ predicted_state

            # Ambiguity
            log_A = jnp.log(A + 1e-16)
            ambiguity = -jnp.sum(predicted_state * jnp.sum(A * log_A, axis=0))

            # Risk (KL from preferred)
            C_norm = jax.nn.softmax(C)
            risk = jnp.sum(predicted_obs * (jnp.log(predicted_obs + 1e-16) - jnp.log(C_norm + 1e-16)))

            efe = efe.at[a_idx].set(ambiguity + risk)

        # 4. Action selection via NumPyro Categorical
        key, subkey = jrandom.split(key)
        action_probs = jax.nn.softmax(-efe)
        action = int(dist.Categorical(probs=action_probs).sample(subkey))

        # 5. State transition
        key, subkey = jrandom.split(key)
        B_a = B[:, :, action]
        transition_probs = B_a[:, true_state]
        transition_probs = transition_probs / (jnp.sum(transition_probs) + 1e-16)
        true_state = int(dist.Categorical(probs=transition_probs).sample(subkey))

        beliefs_history.append(np.array(beliefs).tolist())
        actions_history.append(action)
        observations_history.append(observation)
        efe_history.append(np.array(efe).tolist())

    elapsed = time.time() - start_time

    # --- Validation ---
    beliefs_arr = np.array(beliefs_history)
    validation = {
        "beliefs_in_range": bool(np.all((beliefs_arr >= 0) & (beliefs_arr <= 1))),
        "beliefs_sum_to_one": bool(np.allclose(beliefs_arr.sum(axis=1), 1.0, atol=1e-6)),
        "actions_in_range": all(0 <= a < num_actions for a in actions_history),
        "all_valid": True,
    }
    validation["all_valid"] = all(validation.values())

    results = {
        "model_name": "numpyro_pomdp",
        "framework": "numpyro",
        "num_timesteps": T,
        "num_states": num_states,
        "num_observations": num_obs,
        "num_actions": num_actions,
        "beliefs": beliefs_history,
        "actions": actions_history,
        "observations": observations_history,
        "efe_history": efe_history,
        "validation": validation,
        "execution_time_seconds": round(elapsed, 4),
        "jax_version": jax.__version__,
        "numpyro_version": numpyro.__version__,
    }

    output_dir = Path(os.environ.get("NUMPYRO_OUTPUT_DIR", "."))
    output_dir.mkdir(parents=True, exist_ok=True)
    output_file = output_dir / "simulation_results.json"
    with open(output_file, "w") as f:
        json.dump(results, f, indent=2)

    print(f"NumPyro POMDP simulation complete: {T} timesteps in {elapsed:.3f}s")
    print(f"Results saved to: {output_file}")
    print(f"Validation: {validation}")
    return results


if __name__ == "__main__":
    run_simulation()
