"""
Processor for GUI 2: Visual Matrix Editor

Handles the main processing logic for the visual matrix editing interface.
"""

from __future__ import annotations

import json
import logging
import os
import tempfile
from pathlib import Path
from typing import Any, Optional

from utils.pipeline_template import (
    log_step_error,
    log_step_success,
)

from ..backend import detect_gradio_backend, write_json_atomically
from .matrix_editor import (
    create_matrix_from_gnn,
    get_pomdp_template,
)

_GUI_STATUS = detect_gradio_backend()
gr = _GUI_STATUS.module
_GUI_BACKEND = _GUI_STATUS.name
_GUI_BACKEND_REASON = _GUI_STATUS.reason


def run_gui(
    target_dir: Path,
    output_dir: Path,
    logger: logging.Logger,
    verbose: bool = False,
    headless: bool = False,
    export_filename: str = "visual_model.md",
    open_browser: bool = True,
) -> bool:
    """
    Launch the visual matrix editor GUI or generate artifacts in headless mode.

    Features:
    - Visual matrix representation with drag-and-drop editing
    - Real-time GNN markdown generation
    - POMDP template initialization
    - Interactive state space modification
    """
    try:
        # Setup output directory
        try:
            from pipeline.config import get_output_dir_for_script

            output_root = get_output_dir_for_script("22_gui.py", output_dir)
        except Exception:
            output_root = output_dir

        output_root.mkdir(parents=True, exist_ok=True)

        starter_md = _load_template_markdown(target_dir)
        if starter_md is None:
            starter_md = get_pomdp_template()

        if headless or _GUI_BACKEND is None:
            starter_md = f"<!-- HEADLESS ARTIFACT: Generated by GUI 2 Visual Editor -->\n{starter_md}"

        starter_path = output_root / export_filename
        with tempfile.NamedTemporaryFile(
            mode="w", encoding="utf-8", dir=starter_path.parent, delete=False
        ) as tmp_f:
            tmp_f.write(starter_md)
        os.replace(tmp_f.name, str(starter_path))

        if headless or _GUI_BACKEND is None:
            # Generate headless artifacts for GUI 2
            if _GUI_BACKEND is None:
                if headless:
                    logger.info(
                        "Gradio not installed; generating recovery artifacts only "
                        "(expected for default pipeline — use uv sync --extra gui for interactive UI)"
                    )
                else:
                    logger.warning(
                        "Gradio not available - generating recovery artifacts only"
                    )
                if _GUI_BACKEND_REASON:
                    logger.info(f"GUI backend unavailable: {_GUI_BACKEND_REASON}")
                logger.info("Install GUI support with: uv sync --extra gui")
            else:
                logger.info(
                    "📦 Running GUI 2 in HEADLESS mode - generating artifacts only"
                )

            gui_output_dir = output_root
            gui_output_dir.mkdir(parents=True, exist_ok=True)

            # Create visual matrix representation
            visual_data = create_matrix_from_gnn(starter_md)

            # Save visual data as JSON for potential future loading
            vis_matrices_path = gui_output_dir / "visual_matrices.json"
            write_json_atomically(vis_matrices_path, visual_data)

            # Generate status artifact
            write_json_atomically(
                gui_output_dir / "gui_status.json",
                {
                    "backend": _GUI_BACKEND or "none",
                    "launched": False,
                    "export_file": str(starter_path),
                    "gui_type": "visual_matrix_editor",
                    "status": "fallback_mode"
                    if _GUI_BACKEND is None
                    else "headless_mode",
                    "backend_reason": _GUI_BACKEND_REASON,
                    "visual_data_file": str(gui_output_dir / "visual_matrices.json"),
                    "features": [
                        "Visual matrix editing",
                        "Drag-and-drop interface",
                        "Real-time GNN generation",
                        "POMDP template-based",
                    ],
                    "recommendations": [
                        "Run with --interactive to launch GUI server on port 7861"
                    ]
                    if _GUI_BACKEND
                    else [
                        "Install with: uv sync --extra gui",
                        "Run with --interactive for full GUI experience",
                    ],
                },
            )

            log_step_success(
                logger,
                f"GUI 2 artifacts generated ({'recovery' if _GUI_BACKEND is None else 'headless'}). Export: {starter_path}",
            )
            return True

        # Interactive mode - build visual matrix editor GUI
        logger.info("🔧 Building Visual Matrix Editor UI...")
        from .ui import build_visual_gui

        demo = build_visual_gui(starter_md, starter_path, logger)
        logger.info("✅ Visual Matrix Editor UI built successfully")

        # Launch GUI server with proper threading
        logger.info(
            f"🌐 Launching GUI 2 on http://localhost:7861 (open_browser={open_browser})"
        )

        import threading
        import time

        def launch_gui() -> Any:
            logger.info("🎯 Visual Matrix Editor starting...")
            demo.launch(
                share=False,
                prevent_thread_lock=False,  # Let the thread properly block on the server
                server_name="0.0.0.0",  # nosec B104
                server_port=7861,
                inbrowser=open_browser,
                show_error=True,
                quiet=False,  # Show server startup messages
            )

        # Launch in a separate thread to allow multiple GUIs
        gui_thread = threading.Thread(target=launch_gui, daemon=False)
        gui_thread.start()

        # Give it a moment to start
        time.sleep(3)
        logger.info("🎯 GUI 2 is running on http://localhost:7861")
        logger.info(
            "🔍 Features: Real-time heatmaps, matrix editing, interactive dimension controls, live statistics"
        )

        # Record launch status
        gui_output_dir = output_root
        gui_output_dir.mkdir(parents=True, exist_ok=True)
        write_json_atomically(
            gui_output_dir / "gui_status.json",
            {
                "backend": _GUI_BACKEND,
                "launched": True,
                "export_file": str(starter_path),
                "gui_type": "visual_matrix_editor",
                "port": 7861,
                "url": "http://localhost:7861",
                "features": [
                    "Visual matrix editing",
                    "Drag-and-drop interface",
                    "Real-time GNN generation",
                    "POMDP template-based",
                ],
            },
        )

        log_step_success(logger, "GUI 2 (Visual Matrix Editor) launched successfully")
        return True

    except Exception as e:
        log_step_error(logger, f"GUI 2 launch failed: {e}")
        return False


def _load_template_markdown(target_dir: Path) -> Optional[str]:
    """
    Load template markdown, preferring the POMDP template for visual editing.
    """
    try:
        # Look for specific POMDP files first
        pomdp_files = list(target_dir.glob("*pomdp*.md")) + list(
            target_dir.glob("*POMDP*.md")
        )
        if pomdp_files:
            return pomdp_files[0].read_text()

        # Fall back to any markdown file
        for p in sorted(target_dir.glob("*.md")):
            return p.read_text()

        for p in sorted(target_dir.glob("**/*.md")):
            return p.read_text()

    except Exception:
        return None

    return None
