#!/usr/bin/env python3
"""
jax continuous (linear-Gaussian state-space) simulation: Stochastic Continuous Dynamics Agent

Auto-generated by the GNN pipeline — jax renderer, continuous branch.
Generative model:
    x_1 ~ N(prior_mean, prior_cov)
    x_t = F x_(t-1) + u_(t-1) + N(0, Q)      (2-dim latent state)
    y_t = H x_t + N(0, R)                    (2-dim observation)
Control: passive (u_t = 0)
Inference: online Kalman filter (Joseph-form covariance update).
"""
import json
import os
import sys
import time
from pathlib import Path

import numpy as np

MODEL_NAME = 'Stochastic Continuous Dynamics Agent'
RANDOM_SEED = 42
NUM_TIMESTEPS = 15
DT = 0.1
OUTPUT_ENV = 'GNN_OUTPUT_DIR'

F_RAW = [[1.0, 0.1], [0.0, 0.9]]
H_RAW = [[1.0, 0.0], [1.0, 0.0]]
Q_RAW = [[0.1, 0.0], [0.0, 0.1]]
R_RAW = [[0.2, 0.0], [0.0, 0.2]]
PRIOR_MEAN_RAW = [0.0, 0.0]
PRIOR_COV_RAW = [[0.5, 0.0], [0.0, 1.0]]
GOAL_MEAN_RAW = None
CONTROL_GAIN = None

from jax import config as _jax_config
_jax_config.update('jax_enable_x64', True)

try:
    import jax
    import jax.numpy as jnp
except ImportError:
    print("ERROR: JAX not installed. Install with: uv sync")
    sys.exit(1)

FRAMEWORK = "jax"
FRAMEWORK_VERSION = {"jax_version": jax.__version__}
_KEY = [jax.random.PRNGKey(RANDOM_SEED)]


def arr(x):
    return jnp.asarray(x, dtype=jnp.float64)


def eye(n):
    return jnp.eye(n, dtype=jnp.float64)


def solve(a, b):
    return jnp.linalg.solve(a, b)


def mvn_sample(mean, cov):
    _KEY[0], sub = jax.random.split(_KEY[0])
    return jax.random.multivariate_normal(sub, mean, cov)


def to_list(x):
    return np.asarray(x, dtype=float).tolist()


def is_psd(cov):
    return bool(jnp.all(jnp.linalg.eigvalsh((cov + cov.T) / 2.0) > -1e-9))


def kalman_step(mu, P, y_t, F, H, Q, R, u_prev, first):
    """One predict/update step. ``first`` skips prediction (prior is for x_1)."""
    if first:
        mu_pred, P_pred = mu, P
    else:
        mu_pred = F @ mu + u_prev
        P_pred = F @ P @ F.T + Q
    S = H @ P_pred @ H.T + R
    K = solve(S.T, (P_pred @ H.T).T).T  # P_pred H^T S^{-1}
    innovation = y_t - H @ mu_pred
    mu_new = mu_pred + K @ innovation
    I_KH = eye(P_pred.shape[0]) - K @ H
    P_new = I_KH @ P_pred @ I_KH.T + K @ R @ K.T  # Joseph form (stays PSD)
    return mu_new, P_new


def run_simulation():
    start = time.time()
    F, H, Q, R = arr(F_RAW), arr(H_RAW), arr(Q_RAW), arr(R_RAW)
    prior_mean, prior_cov = arr(PRIOR_MEAN_RAW), arr(PRIOR_COV_RAW)
    goal = arr(GOAL_MEAN_RAW) if GOAL_MEAN_RAW is not None else None
    gain = CONTROL_GAIN
    n, m, T = F.shape[0], H.shape[0], NUM_TIMESTEPS

    zero_u = arr([0.0] * n)
    true_states, observations, beliefs, covs, controls = [], [], [], [], []

    x = mvn_sample(prior_mean, prior_cov)
    y = H @ x + mvn_sample(arr([0.0] * m), R)
    mu, P = kalman_step(prior_mean, prior_cov, y, F, H, Q, R, zero_u, True)
    u = gain * (goal - mu) if goal is not None else zero_u
    for buf, val in ((true_states, x), (observations, y), (beliefs, mu), (covs, P), (controls, u)):
        buf.append(to_list(val))

    for _t in range(1, T):
        x = F @ x + u + mvn_sample(arr([0.0] * n), Q)
        y = H @ x + mvn_sample(arr([0.0] * m), R)
        mu, P = kalman_step(mu, P, y, F, H, Q, R, u, False)
        u = gain * (goal - mu) if goal is not None else zero_u
        for buf, val in ((true_states, x), (observations, y), (beliefs, mu), (covs, P), (controls, u)):
            buf.append(to_list(val))

    beliefs_np = np.asarray(beliefs)
    truth_np = np.asarray(true_states)
    rmse = float(np.sqrt(np.mean((beliefs_np - truth_np) ** 2)))
    psd = all(is_psd(arr(c)) for c in covs)
    validation = {
        "means_finite": bool(np.all(np.isfinite(beliefs_np))),
        "posterior_cov_psd": bool(psd),
        "rmse_finite": bool(np.isfinite(rmse)),
        "controls_finite": bool(np.all(np.isfinite(np.asarray(controls)))),
    }
    results = {
        "model_name": MODEL_NAME,
        "framework": FRAMEWORK,
        "model_kind": "continuous",
        "num_timesteps": T,
        "num_states": n,
        "num_observations": m,
        "beliefs": beliefs,
        "posterior_cov": covs,
        "true_states_continuous": true_states,
        "observations_continuous": observations,
        "controls": controls,
        "control_mode": "closed_loop_proportional" if goal is not None else "passive",
        "rmse_vs_true": rmse,
        # Discrete-schema slots stay empty: nothing categorical is defined here.
        "observations": [],
        "actions": [],
        "efe_history": [],
    }
    if FRAMEWORK == "numpyro":
        mcmc_means, r_hat_max = run_mcmc(
            arr(observations), arr(controls), F, H, Q, R, prior_mean, prior_cov, T, n
        )
        results["mcmc_posterior_means"] = mcmc_means
        results["mcmc_r_hat_max"] = r_hat_max
        results["mcmc_rmse_vs_kalman"] = float(
            np.sqrt(np.mean((np.asarray(mcmc_means) - beliefs_np) ** 2))
        )
        validation["mcmc_finite"] = bool(np.all(np.isfinite(np.asarray(mcmc_means))))
    validation["all_valid"] = all(validation.values())
    results["validation"] = validation
    results["execution_time_seconds"] = round(time.time() - start, 4)
    results.update(FRAMEWORK_VERSION)

    output_dir = Path(os.environ.get(OUTPUT_ENV, "."))
    output_dir.mkdir(parents=True, exist_ok=True)
    out = output_dir / "simulation_results.json"
    with open(out, "w") as f:
        json.dump(results, f, indent=2)
    print(f"{FRAMEWORK} continuous LGSSM simulation complete: {T} steps, rmse_vs_true={rmse:.4f}")
    print(f"Results saved to: {out}")
    print(f"Validation: {validation}")
    return results


if __name__ == "__main__":
    res = run_simulation()
    sys.exit(0 if res["validation"]["all_valid"] else 1)
