#!/usr/bin/env python3
"""F7/F14 regression: gui_1/gui_2 info ports and run_gui export defaults.

Coverage: ``get_available_guis()`` exposes an exact ``port`` int for all
four GUI entries (F7 — gui_1/gui_2 lacked the key pre-fix, while gui_3 and
oxdraw already had 7862/5151), and both processor ``run_gui`` defaults for
``export_filename`` match the wrapper defaults (F14 — pre-fix they wrote
``constructed_model.md`` / ``visual_model.md`` instead of
``constructed_model_gui1.md`` / ``visual_model_gui2.md``).

Failing pre-fix rationale: the port assertions raise on the missing
``port`` key for gui_1/gui_2, and the headless-artifact assertions fail on
the unaligned export filenames.

Tests assert observable artifacts (exported files + status JSON), run
``headless=True`` so they are deterministic with or without gradio, and
need no network or GUI backend.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

import pytest

from gnn.gui import get_available_guis
from gnn.gui.gui_1.processor import run_gui as run_gui_1
from gnn.gui.gui_2.processor import run_gui as run_gui_2

EXPECTED_PORTS = {
    "gui_1": 7860,
    "gui_2": 7861,
    "gui_3": 7862,
    "oxdraw": 5151,
}


class TestGuiInfoPorts:
    """Every available GUI advertises its server port in its info dict."""

    @pytest.mark.unit
    @pytest.mark.fast
    def test_all_four_guis_have_exact_ports(self) -> None:
        guis: dict[str, Any] = get_available_guis()
        assert sorted(guis) == sorted(EXPECTED_PORTS)
        for name, expected_port in EXPECTED_PORTS.items():
            assert guis[name]["port"] == expected_port, name


class TestRunGuiExportDefaults:
    """Default ``export_filename`` produces the wrapper-default filenames."""

    @pytest.mark.unit
    @pytest.mark.fast
    def test_gui1_default_export_filename(self, tmp_path: Path) -> None:
        target = tmp_path / "input"
        output = tmp_path / "22_gui_output"
        target.mkdir()

        assert run_gui_1(
            target_dir=target,
            output_dir=output,
            logger=logging.getLogger("test_gui1_default_export_filename"),
            headless=True,
        )

        export_path = output / "constructed_model_gui1.md"
        assert export_path.is_file()
        assert export_path.read_text(encoding="utf-8").startswith(
            "<!-- HEADLESS ARTIFACT: Generated by GUI 1 Constructor -->"
        )

        status: dict[str, Any] = json.loads(
            (output / "gui_1_status.json").read_text(encoding="utf-8")
        )
        assert status["export_file"].endswith("constructed_model_gui1.md")

    @pytest.mark.unit
    @pytest.mark.fast
    def test_gui2_default_export_filename(self, tmp_path: Path) -> None:
        target = tmp_path / "input"
        output = tmp_path / "22_gui_output"
        target.mkdir()

        assert run_gui_2(
            target_dir=target,
            output_dir=output,
            logger=logging.getLogger("test_gui2_default_export_filename"),
            headless=True,
        )

        export_path = output / "visual_model_gui2.md"
        assert export_path.is_file()
        assert export_path.read_text(encoding="utf-8").startswith(
            "<!-- HEADLESS ARTIFACT: Generated by GUI 2 Visual Editor -->"
        )
        assert (output / "visual_matrices.json").is_file()

        status: dict[str, Any] = json.loads(
            (output / "gui_2_status.json").read_text(encoding="utf-8")
        )
        assert status["export_file"].endswith("visual_model_gui2.md")
