#!/usr/bin/env julia

"""
Multiagent_GNN_RxInfer.jl

This script demonstrates the GNN-RxInfer pipeline for Multi-agent Trajectory Planning.
It performs a two-step validation:
1.  **Baseline Execution:** It runs the original multi-agent trajectory planning example from the `RxInferExamples.jl` package using its original configuration file. This establishes a baseline for behavior and output.
2.  **GNN-Configured Execution:** It creates a copy of the example, but replaces the original `config.toml` with a version generated by the GNN pipeline (`rxinfer_multiagent_gnn_config.toml`). It then runs the simulation using this GNN-derived configuration.

The goal is to verify that a `config.toml` file produced from a GNN specification can correctly configure and drive the RxInfer.jl simulation, thus validating the end-to-end GNN-to-simulation pipeline.

Author: Cursor AI Assistant
Date: 2024-07-25
"""

using Pkg
using Dates
using TOML
using Logging
using Statistics

# Set up logging
log_dir = joinpath(dirname(@__DIR__), "output", "logs")
mkpath(log_dir)
log_file = joinpath(log_dir, "multiagent_gnn_rxinfer_$(Dates.format(now(), "yyyymmdd_HHMMSS")).log")
io = open(log_file, "w+")
# Use only ConsoleLogger for simplicity
global_logger(ConsoleLogger(stderr))

println("Script started")

# Define paths
REPO_ROOT = dirname(dirname(@__DIR__))
RXINFER_EXAMPLES_DIR = joinpath(@__DIR__, "RxInferExamples.jl")
ORIGINAL_SCRIPT_PATH = joinpath(RXINFER_EXAMPLES_DIR, "scripts", "Advanced Examples", "Multi-agent Trajectory Planning", "Multi-agent Trajectory Planning.jl")
ORIGINAL_DIR = dirname(ORIGINAL_SCRIPT_PATH)
TARGET_DIR = joinpath(@__DIR__, "multiagent_trajectory_planning")
GNN_CONFIG_DIR = joinpath(REPO_ROOT, "output", "gnn_rendered_simulators", "rxinfer_toml")
GNN_CONFIG_PATH = joinpath(GNN_CONFIG_DIR, "rxinfer_multiagent_gnn_config.toml")

println("Defined paths:")
println("REPO_ROOT: $REPO_ROOT")
println("RXINFER_EXAMPLES_DIR: $RXINFER_EXAMPLES_DIR")
println("ORIGINAL_SCRIPT_PATH: $ORIGINAL_SCRIPT_PATH")
println("GNN_CONFIG_PATH: $GNN_CONFIG_PATH")

function check_paths_exist()
    @info "Checking required paths..."
    
    if !isfile(ORIGINAL_SCRIPT_PATH)
        @error "Original script not found at: $ORIGINAL_SCRIPT_PATH"
        return false
    end
    
    if !isfile(GNN_CONFIG_PATH)
        @error "GNN-rendered config not found at: $GNN_CONFIG_PATH"
        @info "Looking for alternative config files in output directory..."
        if isdir(GNN_CONFIG_DIR)
            config_files = filter(f -> endswith(f, ".toml"), readdir(GNN_CONFIG_DIR))
            if !isempty(config_files)
                @info "Found potential config files: $config_files"
                @info "Please ensure the path is correct in the script."
            else
                @info "No TOML config files found in output directory: $GNN_CONFIG_DIR"
            end
        else
            @error "GNN config directory does not exist: $GNN_CONFIG_DIR"
        end
        return false
    end
    
    return true
end

function run_original_script()
    @info "Running original Multi-agent Trajectory Planning script..."
    
    # Change to the directory containing the script (for relative paths in the script)
    original_dir = pwd()
    cd(dirname(ORIGINAL_SCRIPT_PATH))
    
    try
        # Capture output from the script execution
        output = read(`julia "$(basename(ORIGINAL_SCRIPT_PATH))"`, String)
        @info "Original script executed successfully"
        @debug "Script output: $output"
    catch e
        @error "Failed to run original script" exception=(e, catch_backtrace())
        cd(original_dir)
        return false
    end
    
    cd(original_dir)
    return true
end

function validate_gnn_config()
    @info "Validating GNN-generated configuration..."
    
    try
        config = TOML.parsefile(GNN_CONFIG_PATH)
        @info "GNN config loaded successfully with $(length(keys(config))) top-level keys"
        
        # Check for essential configuration sections
        essential_sections = ["model", "priors", "visualization", "environments", "agents", "experiments"]
        missing_sections = filter(s -> !haskey(config, s), essential_sections)
        
        if !isempty(missing_sections)
            @warn "GNN config is missing expected sections: $missing_sections"
            return false
        end
        
        return true
    catch e
        @error "Failed to validate GNN config" exception=(e, catch_backtrace())
        return false
    end
end

function copy_and_modify_scripts()
    @info "Copying scripts and replacing configuration..."
    
    # Create target directory if it doesn't exist
    mkpath(TARGET_DIR)
    
    try
        # Copy all files except config.toml
        for file in readdir(ORIGINAL_DIR)
            src_path = joinpath(ORIGINAL_DIR, file)
            dst_path = joinpath(TARGET_DIR, file)
            
            if file != "config.toml" && isfile(src_path)
                cp(src_path, dst_path, force=true)
                @info "Copied $file to target directory"
            end
        end
        
        # Copy the GNN-generated config
        cp(GNN_CONFIG_PATH, joinpath(TARGET_DIR, "config.toml"), force=true)
        @info "Replaced config.toml with GNN-generated version"
        
        return true
    catch e
        @error "Failed to copy and modify scripts" exception=(e, catch_backtrace())
        return false
    end
end

function run_modified_script()
    @info "Running modified script with GNN-generated config..."
    
    # Change to the target directory
    original_dir = pwd()
    cd(TARGET_DIR)
    
    try
        # Find the main script file (assuming it's the same name as the original)
        script_name = basename(ORIGINAL_SCRIPT_PATH)
        
        # Execute the script
        output = read(`julia "$script_name"`, String)
        @info "Modified script executed successfully"
        @debug "Script output: $output"
    catch e
        @error "Failed to run modified script" exception=(e, catch_backtrace())
        cd(original_dir)
        return false
    end
    
    cd(original_dir)
    return true
end

function log_summary(original_dir, gnn_dir, original_script_path)
    println("\n" * "="^25 * " Execution Summary " * "="^25)

    # Helper to format bytes
    format_bytes(bytes) = bytes < 1024 ? "$bytes B" : bytes < 1024^2 ? "$(round(bytes/1024, digits=2)) KB" : "$(round(bytes/1024^2, digits=2)) MB"

    function print_file_details(path, description)
        if isfile(path)
            sz = filesize(path)
            println("  - $description: $(basename(path)) ($(format_bytes(sz)))")
        else
            println("  - $description: $(basename(path)) (Not found)")
        end
    end

    function list_output_files(dir_path)
        results_dir = joinpath(dir_path, "results")
        println("  Output Location: $results_dir")
        if !isdir(results_dir)
            println("    - No output directory found.")
            return
        end
        files = readdir(results_dir)
        if isempty(files)
            println("    - Output directory is empty.")
            return
        end
        for file in files
            path = joinpath(results_dir, file)
            if isfile(path)
                sz = filesize(path)
                println("    - $file ($(format_bytes(sz)))")
            end
        end
    end

    # --- Original Simulation ---
    println("\n[ Original Simulation ]")
    println("  Input Location: $original_dir")
    print_file_details(original_script_path, "Script")
    print_file_details(joinpath(original_dir, "config.toml"), "Config")
    list_output_files(original_dir)

    # --- GNN-Configured Simulation ---
    println("\n[ GNN-Configured Simulation ]")
    println("  Input Location: $gnn_dir")
    print_file_details(joinpath(gnn_dir, basename(original_script_path)), "Script")
    print_file_details(joinpath(gnn_dir, "config.toml"), "GNN Config")
    list_output_files(gnn_dir)

    println("\n" * "="^70 * "\n")
end

function main()
    println("Starting main function")
    @info "Starting Multiagent_GNN_RxInfer.jl script"
    
    # Check if required paths exist
    if !check_paths_exist()
        @error "Required paths check failed. Exiting."
        return 1
    end
    
    # Run the original script to establish baseline
    if !run_original_script()
        @error "Original script execution failed. Exiting."
        return 1
    end
    
    # Validate the GNN-generated config
    if !validate_gnn_config()
        @error "GNN config validation failed. Exiting."
        return 1
    end
    
    # Copy and modify the scripts
    if !copy_and_modify_scripts()
        @error "Failed to prepare modified scripts. Exiting."
        return 1
    end
    
    # Run the modified script
    if !run_modified_script()
        @error "Modified script execution failed. Exiting."
        return 1
    end
    
    @info "Multiagent_GNN_RxInfer.jl completed successfully"
    @info "Original implementation: $ORIGINAL_DIR"
    @info "GNN-based implementation: $TARGET_DIR"
    
    log_summary(ORIGINAL_DIR, TARGET_DIR, ORIGINAL_SCRIPT_PATH)
    
    return 0
end

# Execute the main function
println("Calling main function")
exit_code = 1 # Default exit code
try
    global exit_code = main()
    println("Script completed with exit code: $exit_code")
catch e
    println("Error in main function: ", e)
    println(catch_backtrace())
    global exit_code = 1
finally
    close(io)  # Close the log file
    exit(exit_code)
end 