#!/usr/bin/env python3
"""
DisCoPy Categorical Diagram Generation
Generated from GNN Model: POMDP GridWorld 3x3
Generated: 2026-06-18 07:53:05

This script creates categorical diagrams representing the Active Inference model
structure using DisCoPy's compositional framework.
"""

import sys

try:
    import discopy
except ImportError:
    print("DisCoPy is not installed. Install the project render extras before running this script.")
    sys.exit(1)

from discopy import *
from discopy.monoidal import Ty, Box, Id
from discopy.drawing import Equation
import numpy as np
# Note: Visualizations are generated by the analysis step (16_analysis.py),
# not by this script. This script focuses on circuit construction and data export.
from pathlib import Path
import json

# Model parameters extracted from GNN specification
NUM_STATES = 9
NUM_OBSERVATIONS = 9
NUM_ACTIONS = 5
MATRIX_PERMUTATION_METADATA = {}
MATRIX_PERMUTATION_APPLIED_TO_DIAGRAM = False

def validate_matrix_permutation_metadata(metadata):
    """Validate generated matrix permutation metadata before exporting diagrams."""
    if not isinstance(metadata, dict):
        raise ValueError("Matrix permutation metadata must be a dictionary")
    for matrix_name, record in metadata.items():
        if record.get("axis") != "rows":
            raise ValueError(f"Unsupported permutation axis for {matrix_name}")
        shape = record.get("shape")
        permutation = record.get("permutation")
        if not isinstance(shape, list) or not isinstance(permutation, list):
            raise ValueError(f"Invalid permutation metadata for {matrix_name}")
        if not shape:
            raise ValueError(f"Missing matrix shape for {matrix_name}")
        if len(permutation) != int(shape[0]):
            raise ValueError(f"Permutation length mismatch for {matrix_name}")
        if sorted(int(item) for item in permutation) != list(range(int(shape[0]))):
            raise ValueError(f"Permutation indices mismatch for {matrix_name}")

validate_matrix_permutation_metadata(MATRIX_PERMUTATION_METADATA)

print("🔬 DisCoPy Categorical Diagram Generation")
print(f"📊 State Space: {NUM_STATES} states, {NUM_OBSERVATIONS} observations, {NUM_ACTIONS} actions")

# Define basic types for Active Inference
def define_types():
    """Define the basic types for our Active Inference model."""
    
    # Basic types
    S = Ty('S')  # Hidden states
    O = Ty('O')  # Observations  
    A = Ty('A')  # Actions
    P = Ty('P')  # Probabilities
    
    print("✓ Defined basic types: S (states), O (observations), A (actions), P (probabilities)")
    return S, O, A, P

# Define morphisms (boxes) for model components
def define_model_components(S, O, A, P):
    """Define the morphisms representing Active Inference model components."""
    
    components = {}
    
    # A matrix: Observation model P(o|s)
    components['A_matrix'] = Box('A', S, O @ P)

    # B matrix: Transition model P(s'|s,a)
    components['B_matrix'] = Box('B', S @ A, S @ P)

    # C vector: Preference vector over observations
    components['C_vector'] = Box('C', Ty(), O @ P)

    # D vector: Prior beliefs over states
    components['D_vector'] = Box('D', Ty(), S @ P)

    # E vector: Policy priors (if applicable)
    components['E_vector'] = Box('E', Ty(), A @ P)

    # Inference processes
    components['state_inference'] = Box('StateInf', O, S @ P)
    components['policy_inference'] = Box('PolicyInf', S @ P, A @ P)
    components['action_selection'] = Box('ActionSel', A @ P, A)
    
    print(f"✓ Defined {len(components)} model components as morphisms")
    return components

# Create Active Inference circuit
def create_active_inference_circuit(S, O, A, P, components):
    """Create the full Active Inference circuit as a categorical diagram."""
    
    print("\n🏗️  Building Active Inference circuit...")
    
    # Extract components
    A_matrix = components['A_matrix']
    B_matrix = components['B_matrix'] 
    C_vector = components['C_vector']
    D_vector = components['D_vector']
    state_inf = components['state_inference']
    policy_inf = components['policy_inference']
    action_sel = components['action_selection']
    
    # Basic perception-action loop
    # Observation -> State Inference -> Policy Inference -> Action Selection
    perception_action_loop = (
        state_inf 
        >> policy_inf 
        >> action_sel
    )
    
    # Full generative model - compose priors alongside the inference loop (D-3 fix)
    # D_vector and C_vector enter as parallel tensor products
    try:
        # Compose: (D_vector @ C_vector) provides initial state and preference priors
        prior_block = D_vector @ C_vector
        generative_model = prior_block >> (state_inf @ Id(P)) >> policy_inf >> action_sel
        print("✓ Created generative model with composed priors")
    except Exception as e:
        # Recovery: type mismatch means priors cannot directly compose
        print(f"⚠️  Prior composition type mismatch ({e}), using perception-action loop")
        generative_model = perception_action_loop
    
    print("✓ Created perception-action loop")
    
    return {
        'perception_action_loop': perception_action_loop,
        'generative_model': generative_model,
        'components': components
    }



# Analysis functions
def analyze_circuit_structure(circuit_dict):
    """Analyze the structure of the categorical diagrams."""
    
    print("\n🔍 Analyzing circuit structure...")
    
    components = circuit_dict['components']
    loop = circuit_dict['perception_action_loop']
    model = circuit_dict['generative_model']
    
    # Basic structural analysis
    print(f"📊 Circuit Analysis:")
    print(f"  - Number of components: {len(components)}")
    print(f"  - Perception-action loop domain: {loop.dom}")
    print(f"  - Perception-action loop codomain: {loop.cod}")
    print(f"  - Generative model domain: {model.dom}")
    print(f"  - Generative model codomain: {model.cod}")
    
    # Component analysis
    print(f"\n🧩 Component Details:")
    for name, component in components.items():
        print(f"  - {name}: {component.dom} → {component.cod}")
    
    # Compositional structure
    print(f"\n🔗 Compositional Structure:")
    print(f"  - Loop composition depth: {len(str(loop).split('>>'))}")
    print(f"  - Model composition depth: {len(str(model).split('>>'))}")
    
    return {
        'num_components': len(components),
        'loop_domain': str(loop.dom),
        'loop_codomain': str(loop.cod),
        'model_domain': str(model.dom),
        'model_codomain': str(model.cod)
    }

# Export functions
def export_circuit_data(circuit_dict, analysis_results, output_dir="discopy_diagrams"):
    """Export circuit data and analysis results."""
    
    print(f"\n💾 Exporting circuit data to {output_dir}/...")
    
    Path(output_dir).mkdir(exist_ok=True)
    
    # Export analysis results
    analysis_file = Path(output_dir) / "circuit_analysis.json"
    with open(analysis_file, 'w') as f:
        json.dump(analysis_results, f, indent=2)
    
    print(f"✓ Exported analysis: {analysis_file}")
    
    # Export circuit information
    circuit_info = {
        'model_name': 'POMDP GridWorld 3x3',
        'timestamp': '2026-06-18 07:53:05',
        'parameters': {
            'num_states': NUM_STATES,
            'num_observations': NUM_OBSERVATIONS, 
            'num_actions': NUM_ACTIONS
        },
        'components': list(circuit_dict['components'].keys()),
        'matrix_permutation_metadata': MATRIX_PERMUTATION_METADATA,
        'matrix_permutation_applied_to_diagram': MATRIX_PERMUTATION_APPLIED_TO_DIAGRAM,
        'analysis': analysis_results
    }
    
    circuit_file = Path(output_dir) / "circuit_info.json"
    with open(circuit_file, 'w') as f:
        json.dump(circuit_info, f, indent=2)
    
    print(f"✓ Exported circuit info: {circuit_file}")

# Main execution
def main():
    """Main execution function."""
    
    print("="*60)
    print("DisCoPy Categorical Diagrams - GNN Generated")
    print(f"Model: POMDP GridWorld 3x3")
    print("="*60)
    
    try:
        # Define types
        S, O, A, P = define_types()
        
        # Define model components
        components = define_model_components(S, O, A, P)
        
        # Create Active Inference circuit
        circuit_dict = create_active_inference_circuit(S, O, A, P, components)
        
        # Analyze circuit structure
        analysis_results = analyze_circuit_structure(circuit_dict)
        
        # Export data
        export_circuit_data(circuit_dict, analysis_results)
        
        print("\n✅ DisCoPy categorical diagram generation completed successfully!")
        print("📊 Circuit analysis and data export successful")
        
        print("\n🎉 Categorical representation of Active Inference model complete!")
        
        return 0
        
    except Exception as e:
        print(f"❌ Diagram generation failed: {e}")
        print("🔍 Stack trace:")
        import traceback
        traceback.print_exc()
        return 1

if __name__ == "__main__":
    exit(main())
