"""
GNN Specification Generator for PyMDP Scaling Analysis.

Provides deterministic generation of stochastic GNN specifications
for the PyMDP runtime scaling sweep. Extracted from the main
orchestrator script for modularity and testing.
"""

from __future__ import annotations

# Default noise parameters
DEFAULT_A_SIGNAL = 0.85   # probability of correct observation
DEFAULT_B_SIGNAL = 0.80   # probability of intended transition

def _fmt_row(vals: list[float]) -> str:
    """Format a row of floats for GNN matrix notation."""
    return "(" + ", ".join(f"{v:.6f}" for v in vals) + ")"


def _make_A(n: int, signal: float) -> str:
    """Generate noisy likelihood matrix A[n,n] as GNN block."""
    noise = (1.0 - signal) / n
    rows = []
    for i in range(n):
        row = [noise] * n
        row[i] = signal + noise
        rows.append("  " + _fmt_row(row))
    return "A={\n" + ",\n".join(rows) + "\n}"


def _make_B(n: int, signal: float) -> str:
    """Generate noisy transition tensor B[n,n,n] as GNN block."""
    noise = (1.0 - signal) / n
    action_slices = []
    for a in range(n):
        row = [noise] * n
        row[a] = signal + noise
        row_str = _fmt_row(row)
        slice_rows = ", ".join([row_str] * n)
        action_slices.append("  ( " + slice_rows + " )")
    return "B={\n" + ",\n".join(action_slices) + "\n}"


def _make_C(n: int) -> str:
    """Preference vector: strong preference for last state."""
    vals = ["0.0"] * n
    vals[-1] = "3.0"
    return "C={(" + ", ".join(vals) + ")}"


def _make_D(n: int) -> str:
    """Uniform prior over hidden states."""
    val = f"{1.0 / n:.6f}"
    return "D={(" + ", ".join([val] * n) + ")}"


def generate_gnn_file(
    n: int,
    t: int,
    a_signal: float = DEFAULT_A_SIGNAL,
    b_signal: float = DEFAULT_B_SIGNAL,
) -> str:
    """Generate a complete GNN spec file for given N and T."""
    return f"""# GNN Example: PyMDP Scaling N{n} T{t}
# GNN Version: 1.0

## GNNSection
ActInfPOMDP

## GNNVersionAndFlags
GNN v1

## ModelName
PyMDP Scaling N{n} T{t}

## ModelAnnotation
PyMDP runtime scaling sweep with noisy observation and stochastic transitions.

## StateSpaceBlock
s[{n},1,type=float]
o[{n},1,type=int]
A[{n},{n},type=float]
B[{n},{n},{n},type=float]
C[{n},type=float]
D[{n},type=float]
pi[{n},type=float]
u[1,type=int]
G[pi,type=float]
F[1,type=float]
t[1,type=int]

## Connections
D>s
s-A
A-o
s-B
C>G
G>pi
pi>u
B>u
s-F
o-F

## InitialParameterization
{_make_A(n, a_signal)}

{_make_B(n, b_signal)}

{_make_C(n)}

{_make_D(n)}

## Equations
# Standard Active Inference update equations

## Time
Time=t
Dynamic
Discrete
ModelTimeHorizon={t}

## ActInfOntologyAnnotation
A=LikelihoodMatrix
B=TransitionMatrix
C=LogPreferenceVector
D=PriorOverHiddenStates
G=ExpectedFreeEnergy
F=VariationalFreeEnergy
s=HiddenState
o=Observation
pi=PolicyVector
u=Action
t=Time

## ModelParameters
num_hidden_states: {n}
num_obs: {n}
num_actions: {n}
num_timesteps: {t}

## Footer
Generated by PyMDP Scaling Suite (noisy: A_signal={a_signal}, B_signal={b_signal}).

## Signature
Cryptographic signature goes here
"""


def estimate_gnn_file_bytes(
    n: int,
    t: int,
    a_signal: float = DEFAULT_A_SIGNAL,
    b_signal: float = DEFAULT_B_SIGNAL,
) -> int:
    """Conservative upper bound on UTF-8 size of :func:`generate_gnn_file` output.

    The B block dominates: ``n`` action slices, each with ``n`` repeated rows of ``n`` floats.
    """
    if n < 1 or t < 1:
        return 0
    # A: n lines × ~n floats × ~20 bytes
    a_bytes = n * n * 22
    # B: n × (n rows × ~n floats) × ~22 bytes, plus separators
    b_bytes = n * n * n * 24
    # C, D, static sections, and horizon
    _ = a_signal, b_signal
    rest = 12_000 + len(str(t)) * 4
    return a_bytes + b_bytes + rest
