// Generated by the GNN pipeline — Stan renderer (discrete POMDP / HMM).
//
// Latent categorical chain marginalised with the forward algorithm.
// Data: observed outcomes o[t] and the actions u[t] that drove the chain,
// the known action-conditioned transition tensor B[a][s_next, s_prev] and the
// prior D. Parameters: the per-state observation distributions A_est[s]
// (columns of the GNN likelihood A), with Dirichlet priors centred on the
// GNN's declared A. Transformed parameters expose the filtered posteriors.
data {
  int<lower=1> T;                              // timesteps
  int<lower=1> S;                              // hidden states
  int<lower=1> O;                              // observation outcomes
  int<lower=1> U;                              // actions
  array[T] int<lower=1, upper=O> o;            // observations (1-based)
  array[T - 1] int<lower=1, upper=U> u;        // actions taken at t=1..T-1
  array[U] matrix[S, S] B;                     // B[a][s_next, s_prev], columns sum to 1
  array[S] vector<lower=0>[O] alpha_A;         // Dirichlet pseudo-counts per state
  simplex[S] D;                                // prior over the initial state
}
parameters {
  array[S] simplex[O] A_est;                   // P(o | s) for each state s
}
transformed parameters {
  // Scaled forward algorithm, vectorised: alpha_t ∝ A[o_t, :] .* (B[u_{t-1}] alpha_{t-1}).
  // Scaling by the per-step normaliser c_t keeps the recursion in probability
  // space (no underflow) and yields log p(o_1..T) = sum_t log c_t.
  array[T] vector[S] filtered_state;           // P(s_t | o_1..t, u_1..t-1)
  real log_marginal = 0;
  {
    matrix[O, S] A_mat;                        // A_mat[o, s] = P(o | s)
    for (s in 1:S) {
      A_mat[:, s] = A_est[s];
    }
    vector[S] alpha = D .* (A_mat[o[1], :])';
    real c = sum(alpha) + 1e-300;
    log_marginal += log(c);
    alpha /= c;
    filtered_state[1] = alpha;
    for (t in 2:T) {
      alpha = (B[u[t - 1]] * alpha) .* (A_mat[o[t], :])';
      c = sum(alpha) + 1e-300;
      log_marginal += log(c);
      alpha /= c;
      filtered_state[t] = alpha;
    }
  }
}
model {
  for (s in 1:S) {
    A_est[s] ~ dirichlet(alpha_A[s]);
  }
  target += log_marginal;                      // marginal likelihood of o[1:T]
}
