"""Processor for GUI 2: Visual Matrix Editor.

Handles the main processing logic for the visual matrix editing interface.
"""

from __future__ import annotations

import logging
import time
from pathlib import Path

from gnn.utils.observability.structured_logging import (
    log_step_error,
    log_step_success,
)

from ..backend import (
    detect_gradio_backend,
    write_json_atomically,
    write_text_atomically,
)
from ..runner import launch_gradio_in_thread, load_first_markdown, resolve_output_root
from .matrix_editor import (
    create_matrix_from_gnn,
    get_pomdp_template,
)

# Detected once at import; tests reload this module after stubbing ``gradio``
# in sys.modules, so this module-level detection must stay.
_GUI_STATUS = detect_gradio_backend()
gr = _GUI_STATUS.module
_GUI_BACKEND = _GUI_STATUS.name
_GUI_BACKEND_REASON = _GUI_STATUS.reason

_GUI2_PORT = 7861


def run_gui(
    target_dir: Path,
    output_dir: Path,
    logger: logging.Logger,
    verbose: bool = False,
    headless: bool = False,
    export_filename: str = "visual_model.md",
    open_browser: bool = True,
) -> bool:
    """
    Run GUI 2: generate headless artifacts or launch the visual matrix editor.

    Args:
        target_dir: Directory containing GNN files to load (prefers POMDP templates)
        output_dir: Output directory for results
        logger: Logger instance
        verbose: Enable verbose logging
        headless: Generate artifacts only, without launching a server
        export_filename: Filename for the exported model
        open_browser: Open the browser automatically in interactive mode

    Returns:
        True on success, False on failure
    """
    try:
        output_root = resolve_output_root(output_dir)
        output_root.mkdir(parents=True, exist_ok=True)

        starter_md = (
            load_first_markdown(
                target_dir, prefer_patterns=("*pomdp*.md", "*POMDP*.md")
            )
            or get_pomdp_template()
        )

        if headless or _GUI_BACKEND is None:
            starter_md = f"<!-- HEADLESS ARTIFACT: Generated by GUI 2 Visual Editor -->\n{starter_md}"

        starter_path = output_root / export_filename
        write_text_atomically(starter_path, starter_md)

        if headless or _GUI_BACKEND is None:
            # Generate headless artifacts for GUI 2
            if _GUI_BACKEND is None:
                logger.info(
                    "Gradio not available; generating static headless GUI 2 "
                    "artifacts (expected for default pipeline; use "
                    "uv sync --extra gui for interactive UI)"
                )
                if _GUI_BACKEND_REASON:
                    logger.info(f"GUI backend unavailable: {_GUI_BACKEND_REASON}")
                logger.info("Install GUI support with: uv sync --extra gui")
            else:
                logger.info(
                    "📦 Running GUI 2 in HEADLESS mode - generating artifacts only"
                )

            # Create visual matrix representation
            visual_data = create_matrix_from_gnn(starter_md)

            # Save visual data as JSON for potential future loading
            vis_matrices_path = output_root / "visual_matrices.json"
            write_json_atomically(vis_matrices_path, visual_data)

            # Generate status artifact
            write_json_atomically(
                output_root / "gui_status.json",
                {
                    "backend": _GUI_BACKEND or "none",
                    "launched": False,
                    "export_file": str(starter_path),
                    "gui_type": "visual_matrix_editor",
                    "status": "static_headless_mode"
                    if _GUI_BACKEND is None
                    else "headless_mode",
                    "backend_reason": _GUI_BACKEND_REASON,
                    "visual_data_file": str(vis_matrices_path),
                    "features": [
                        "Visual matrix editing",
                        "Drag-and-drop interface",
                        "Real-time GNN generation",
                        "POMDP template-based",
                    ],
                    "recommendations": [
                        "Run with --interactive to launch GUI server on port 7861"
                    ]
                    if _GUI_BACKEND
                    else [
                        "Install with: uv sync --extra gui",
                        "Run with --interactive for full GUI experience",
                    ],
                },
            )

            log_step_success(
                logger,
                f"GUI 2 artifacts generated ({'recovery' if _GUI_BACKEND is None else 'headless'}). Export: {starter_path}",
            )
            return True

        # Interactive mode - build visual matrix editor GUI
        logger.info("🔧 Building Visual Matrix Editor UI...")
        from .ui import build_visual_gui

        demo = build_visual_gui(starter_md, starter_path, logger)
        logger.info("✅ Visual Matrix Editor UI built successfully")

        # Launch GUI server with proper threading
        logger.info(
            f"🌐 Launching GUI 2 on http://localhost:{_GUI2_PORT} (open_browser={open_browser})"
        )
        launch_gradio_in_thread(demo, port=_GUI2_PORT, open_browser=open_browser)

        # Give it a moment to start
        time.sleep(3)
        logger.info(f"🎯 GUI 2 is running on http://localhost:{_GUI2_PORT}")
        logger.info(
            "🔍 Features: Real-time heatmaps, matrix editing, interactive dimension controls, live statistics"
        )

        # Record launch status
        write_json_atomically(
            output_root / "gui_status.json",
            {
                "backend": _GUI_BACKEND,
                "launched": True,
                "export_file": str(starter_path),
                "gui_type": "visual_matrix_editor",
                "port": _GUI2_PORT,
                "url": f"http://localhost:{_GUI2_PORT}",
                "features": [
                    "Visual matrix editing",
                    "Drag-and-drop interface",
                    "Real-time GNN generation",
                    "POMDP template-based",
                ],
            },
        )

        log_step_success(logger, "GUI 2 (Visual Matrix Editor) launched successfully")
        return True

    except Exception as e:
        log_step_error(logger, f"GUI 2 launch failed: {e}")
        return False
