"# Multi-agent Trajectory Planning Configuration" = ""
[[agents]]
id = 1
radius = 2.0
initial_position = [ -5.0, 5.0,]
target_position = [ 5.0, -5.0,]

[[agents]]
id = 2
radius = 1.5
initial_position = [ 5.0, 5.0,]
target_position = [ -5.0, -5.0,]

[model]
name = "TestAgentModel"
description = "Test multi-agent model for RxInfer rendering"
dt = 1.0
gamma = 1.0
nr_steps = 30
nr_iterations = 350
nr_agents = 2
softmin_temperature = 10.0
intermediate_steps = 10
save_intermediates = false

[priors]
initial_state_variance = 100.0
control_variance = 0.1
goal_constraint_variance = 1e-5
gamma_shape = 1.5
gamma_scale_factor = 0.5

[visualization]
x_limits = [ -20, 20,]
y_limits = [ -20, 20,]
fps = 15
heatmap_resolution = 100
plot_width = 800
plot_height = 400
agent_alpha = 1.0
target_alpha = 0.2
color_palette = "tab10"

[experiments]
seeds = [ 42, 100,]
results_dir = "test_results"
animation_template = "{environment}_{seed}.gif"
control_vis_filename = "control_signals.gif"
obstacle_distance_filename = "obstacle_distance.png"
path_uncertainty_filename = "path_uncertainty.png"
convergence_filename = "convergence.png"

[model.matrices]
A = [ [ 1.0, 1.0, 0.0, 0.0,], [ 0.0, 1.0, 0.0, 0.0,], [ 0.0, 0.0, 1.0, 1.0,], [ 0.0, 0.0, 0.0, 1.0,],]
B = [ [ 0.0, 0.0,], [ 1.0, 0.0,], [ 0.0, 0.0,], [ 0.0, 1.0,],]
C = [ [ 1.0, 0.0, 0.0, 0.0,], [ 0.0, 0.0, 1.0, 0.0,],]

[environments.default]
description = "Default environment"
obstacles = []
